searchSpaceFile: arima-space-exp12.json
trialCommand: python3 arima-nni.py  # NOTE: change "python3" to "python" if you are using Windows
trialConcurrency: 1
tuner:
  name: GridSearch
trainingService:
  platform: local